config/routes.rb
RebelFoundation::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    match "logout" => "devise/sessions#destroy", as: "logout"  
    match "login" => "devise/sessions#new", as: "login"  
    match "signup" => "devise/registrations#new", as: "signup"
    match "dashboard" => "users#dashboard", as: "dashboard"
    match "admin"=> "users#index", as: "admin"
  end

  match "web_to_lead" => "leads#new_web_lead", :as => "web_to_lead"
  match "create_lead" => "leads#create_web_lead", :as => "create_lead"
  match "generate" => "leads#external_form"
  
  resources :organizations
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      get :convert
    end
  end

  resources :users do
    member do
      get :approve
    end
  end
  

  resources :tasks
  resources :contacts
  resources :accounts
  resources :opportunities
  
  
  root to: 'pages#index'
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String,  :default => ""
  field :encrypted_password, :type => String,  :default => ""
  field :approved,           :type => Boolean, :default => false
  field :admin,              :type => Boolean, :default => false

  validates_presence_of :email
  validates_uniqueness_of :email
  validates_presence_of :encrypted_password
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  has_many :leads

  field :first_name
  field :last_name
  field :company
  field :phone

  def full_name
    self.first_name + " " + self.last_name
  end

  def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message
    end 
  end

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!#, only: :index

  def dashboard
    @leads = Lead.where(lead_owner: current_user.email).to_a
    @tasks = Task.where(assigned_to: current_user.email).to_a
  end

  def index
    @approved_users = User.all.select {|user| user.approved}
    @pending_users = User.all.reject {|user| user.approved}
  end

  def approve
    @user = User.find params[:id]
    @user.update_attributes(approved: true)
    if @user.save
      redirect_to :back, flash: { notice: 'User has successfully been appproved'}
      UserMailer.notify_approval(@user).deliver
    else
      redirect_to :back, flash: { notice: 'Unable to approve user'}
    end
  end

  def destroy
    @user = User.find params[:id]
    if @user.destroy
      redirect_to :back, flash: { notice: 'User has successfully been deleted'}
    else
      redirect_to :back, flash: { notice: 'Unable to delete user'}
    end 
  end

end

app/views/users/dashboard.html.haml
.well
  %h2
    Welcome to your Dashboard
  %hr
  %h4
    Leads assigned:
  %table.table.table-striped
    %thead
      %tr
        %th
          Name
        %th
          Company
        %th
          Status
        %th
          Created Date
    %tbody
      - @leads.each do |lead|
        %tr
          %td
            = link_to lead.full_name.titleize, lead_path(lead)
          %td
            = lead.company
          %td
            = lead.lead_status.to_s.capitalize
          %td
            = lead.created_at.to_date
  %br
  %hr
  %h4
    Tasks assigned:
  %table.table.table-striped
    %thead
      %tr
        %th
          Name
        %th
          Due Date
        %th
          Task Type
        %th
          Lead
    %tbody
      - @tasks.sort_by(&:due_date).each do |task|
        %tr
          %td
            = link_to task.task_name.titleize, task_path(task)
          %td
            = task.due_date
          %td
            = task.task_type.titleize
          %td
            = task.lead_for_task

          

app/views/users/index.html.haml
.well
  %table.table.table-striped.pending-users
    %h3
      Pending Users
    %thead
      %tr
        %th
          Email
        %th
          Name
        %th
          Approved
        %th
          Actions
    %tbody
      - @pending_users.each do |user|
        %tr
          %td
            = user.email
          %td
            = user.full_name
          %td
            = user.approved
          %td
            = link_to "Approve", approve_user_path(user), class: 'btn btn-mini btn-primary'
            = link_to "Delete", user, confirm: "Are you sure you want to delete: #{user.email} ?", method: :delete, class: 'btn btn-mini btn-danger'

.well
  %table.table.table-striped.approved-users
    %h3
      Approved Users
    %thead
      %tr
        %th
          Email
        %th
          Name
        %th
          Approved
        %th
          Actions
    %tbody
      - @approved_users.each do |user|
        %tr
          %td
            = user.email
          %td
            = user.full_name
          %td
            = user.approved
          %td
            = link_to "Delete", user, confirm: "Are you sure you want to delete: #{user.email} ?", method: :delete, class: 'btn btn-mini btn-primary'