config/routes.rb
RebelFoundation::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    match "logout" => "devise/sessions#destroy", as: "logout"  
    match "login" => "devise/sessions#new", as: "login"  
    match "signup" => "devise/registrations#new", as: "signup"
    match "dashboard" => "users#dashboard", as: "dashboard"
    match "admin"=> "users#index", as: "admin"
  end

  match "web_to_lead" => "leads#new_web_lead", :as => "web_to_lead"
  match "create_lead" => "leads#create_web_lead", :as => "create_lead"
  match "generate" => "leads#external_form"
  
  resources :organizations
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      get :convert
    end
  end

  resources :users do
    member do
      get :approve
    end
  end
  

  resources :tasks
  resources :contacts
  resources :accounts
  resources :opportunities
  
  
  root to: 'pages#index'
end

app/models/lead.rb
class Lead < Contact  
  field :interested_in
  field :comments
  field :lead_status
  field :lead_source
  field :lead_owner
  field :account_name
  field :opportunity_name
  field :opportunity_owner

  belongs_to :assigned_to, class_name: 'User'
  has_many :notes
  accepts_nested_attributes_for :notes, allow_destroy: true
  validates_presence_of :lead_owner

  STATUS      = [['New', 'new'], ['Contacted', 'contacted'], ['Qualified', 'qualified'], ['Disqualified', 'disqualified']]
  SOURCES     = [['Web Lead', 'web'], ['Phone', 'phone'], ['Referral', 'referral'], ['Conference', 'conference']]
  INTERESTS   = [['Web Application', 'web_app'], ['IOS', 'ios']]

  class << self
    
    def status
      STATUS
    end
    
    def sources
      SOURCES
    end

    def interests
      INTERESTS
    end
    
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :authenticate_user!, :except => ['external_form']
  
  def new
    @lead = Lead.new
    @lead_owner     = User.all.map(&:email)
    @lead_status    = Lead.status
    @lead_sources   = Lead.sources
    @lead_interests = Lead.interests
  end
  
  def create
    @lead = Lead.new params[:lead]
    @lead.update_attributes(assigned_to: @lead.lead_owner)
    if @lead.save
      LeadMailer.notify_new_lead(@lead.lead_owner, @lead).deliver
      redirect_to lead_path @lead, flash[:notice] = 'New Lead Created'
    else
      render :new
    end
  end
  
  def index
    @leads = Lead.all
  end
  
  def show
    @lead = Lead.find params[:id]
    @lead_owner     = User.all.map(&:email)
    @lead_status    = Lead.status
    @lead_sources   = Lead.sources
    @lead_interests = Lead.interests
  end
  
  def edit
  end
  
  def update
    @lead = Lead.find params[:id]
    if params[:commit] == 'Convert'
      convert_lead
    else  
      if @lead.update_attributes params[:lead]
        LeadMailer.notify_updated_lead(@lead.lead_owner, @lead).deliver
        redirect_to lead_path @lead, flash[:notice] = 'Lead Updated'
      else
        render :edit
      end
    end
  end
  
  def destroy
    @lead = Lead.find params[:id]
    
    if @lead.destroy
      flash[:notice] = 'Lead Deleted'
      redirect_to :back
    else
      flash[:error] = 'Lead could not be deleted'
      redirect_to :back
    end
  end

  def convert
    @lead               = Lead.find params[:id]
    @accounts           = Account.all.map(&:name)
    @opportunity_owner  = User.all.map(&:email)
  end

  def convert_lead
    @lead = Lead.find params[:id]
    @lead.update_attributes params['lead']
    @account = Account.where(name: params['account_name']).first
    @contacts = Contact.all.map(&:email)
    unless @contacts.include? @lead.email
      @contact = Contact.create params['lead']
    end
    @opportunities = Opportunity.all.map(&:opportunity_name)
    unless @opportunities.include? @lead.opportunity_name
      @opportunity = Opportunity.create(opportunity_name: @lead.opportunity_name, account_name: @lead.account_name, owner: @lead.opportunity_owner)
    end
    flash[:notice] = 'Lead has been converted'
    redirect_to opportunity_path(@opportunity)
  end

  def new_web_lead
    leads = Lead.new
    minus_lead = ["_type","_id","created_at", "updated_at", "lead_source", "lead_status","lead_owner", "account_name","opportunity_name","opportunity_owner","assigned_to_id", "interested_in"]
    lead = leads.attribute_names.to_a
    @lead = lead-minus_lead
  end

  def create_web_lead
    @in_lead = []
    default_url = "http://demo.railscrm.com" #CHANGE THIS TO A VALID URL
    fields = ["first_name","last_name", "email", "company", "phone", "address", "city", "state", "zip", "comments"]
    fields.each do |field|
      if params["#{field}"].present?
        @in_lead << field
      end
    end
    @value=""
    @required="required"
    @lead_owner = encrypt(current_user.email)
    @redirect_url = params[:redirect_url].empty? ? default_url : params[:redirect_url]
    render "web_form"
  end

  def external_form
    email = decrypt(params[:lead_owner])
    user = User.where(:email =>email).first
    requestor = "#{request.protocol}#{request.fullpath}"
    if user.nil?
      redirect_to requestor
    else
      redirect_url = params[:redirect_url]
      leads = params[:params].split(" ")
      @lead = Lead.new
      leads.each do |lead|
        @lead.update_attribute("#{lead}", params["#{lead}"])
      end
      @lead.update_attributes(:lead_owner => email,:lead_source => requestor)
      if @lead.save!
        LeadMailer.notify_web_form_lead(@lead.lead_owner, @lead).deliver
        redirect_to redirect_url
      end
    end
  end

  private
    def encrypt(data)
      return encrypted_data = KEY.enc(data)
    end

    def decrypt(encrypted_data)
      return data = KEY.dec(encrypted_data)
    end
end  

app/views/leads/_form.html.haml
.form-horizontal
  = simple_form_for @lead, :html => { :class => 'form-horizontal' }  do |f|
    %fieldset
      %legend Lead Info
      .row
        .span4
          = f.input :first_name
          = f.input :last_name
          = f.input :email, as: :email
          = f.input :phone
          = f.input :company
          = f.input :comments, as: :text, :input_html => {rows: 5}
        .span4
          = f.input :lead_owner,      collection:(@lead_owner)
          = f.input :interested_in,   collection:(@lead_interests)
          = f.input :lead_status,     collection:(@lead_status)
          = f.input :lead_source,     collection:(@lead_sources)


    %fieldset
      %legend Address Info
      .row
        .span4
          = f.input :address
          = f.input :city
        .span4
          = f.input :state
          = f.input :zip
      %br
      .row.pull-right 
        = f.submit class: 'btn btn-primary'
        = link_to 'Cancel', leads_path, class: "btn btn-danger"

app/views/leads/convert.html.haml
.form.well
  .label
    %h2
      Convert Lead
  %br
  .form-horizontal
    = simple_form_for @lead, :html => { :class => 'form-horizontal' }  do |f|
      %fieldset
        %legend Lead Info
        .row.span10
          .span4
            = f.input :first_name
            = f.input :last_name
            = f.input :email, as: :email
            = f.input :phone
            = f.input :company
          .span4.offset1
            = f.input :account_name, collection:(@accounts)
            = f.input :opportunity_name
            = f.input :opportunity_owner, collection:(@opportunity_owner)

      .row.pull-right
        = f.submit 'Convert', class: 'btn btn-primary'  

app/views/leads/convert_form.html.haml
=javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"
=javascript_include_tag "http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js"
=form_tag("http://demo.railscrm.com/generate",name: "web_form", id: "web_form", class: "web_form") do
  =hidden_field_tag :lead_owner, @lead_owner
  =hidden_field_tag :params, @in_lead
  =hidden_field_tag :redirect_url, @redirect_url
  -for a in 0..@in_lead.size-1 do
    =label_tag @in_lead[a]
    -if @in_lead[a] == 'email'
      =text_field_tag @in_lead[a], @value, class: "required email"
    -else
      =text_field_tag @in_lead[a], @value, class: "required"
    %br

  =submit_tag "Submit", class: 'btn btn-primary'
%script 
  $("#web_form").validate();

app/views/leads/index.html.haml
.well
  .functions.pull-right
    = link_to 'Create Lead', new_lead_path, class: 'btn btn-mini'
  %table.table.table-striped
    %thead
      %tr
        %th
          Name
        %th
          Company
        %th
          Phone
        %th
          Status
        %th
          Assigned to
        %th
          Created Date
        %th
          Actions
    %tbody
      - @leads.each do |lead|
        %tr
          %td
            = lead.full_name
          %td
            = lead.company
          %td
            = lead.phone
          %td
            = lead.lead_status.to_s.capitalize
          %td
            = lead.lead_owner
          %td
            = lead.created_at.to_date
          %td
            = link_to 'Edit', lead_path(lead), class: 'btn btn-mini btn-primary'
              
            = link_to 'Delete', lead_path(lead), method: 'delete', class: 'btn btn-mini btn-danger', data: {confirm: 'Are you sure that you want to delete this lead?'}

app/views/leads/new.html.haml
.form.well
  .label
    %h2
      Create New Lead
  %br
    = render partial: 'form'

app/views/leads/new_web_lead.html.haml
.form.well
  .label
    %h2
      New Web Form
  %br
  .span12.offset9
  %p
    The Web-to-Lead form generator is used to create the form code that can be used on your website as a way to create leads from visitors.
  %p
    The Redirect URL is the page that you want to redirect to after the form is submitted. Select the fields that you want your form to have and click "Create Form".
  %br
  .form-horizontal
    =form_tag create_lead_path,:class => 'simple_form' do
      %fieldset
        %legend Lead Info
        .row
          .span9
            %p
              Redirect URL
              =text_field_tag :redirect_url
            %br
        .row
          .span4
            -for a in 0..@lead.size - 1 do
              =check_box_tag @lead[a]
              =@lead[a].titleize
              %br

        %br
        = submit_tag "Create Form", class: 'btn btn-primary'
        = link_to 'Cancel', leads_path, class: "btn btn-danger"

app/views/leads/show.html.haml
.form.well
  .label
    %h2
      View Lead
  %br
    .pull-right
      = link_to 'Convert Lead', convert_lead_path(@lead), data: {toggle: 'modal'}, class: 'btn btn-primary'
    = render partial: 'form'

  %fieldset 
    %legend Lead Activities
    %h3
      Recent Activity for #{@lead.full_name}
      .pull-right
        %a{"data-target" => ".new-note", "data-toggle" => "collapse", class: 'btn btn-primary', id: 'new-note'}
          New Note
    .row.new-note.collapse
      .span9.offset2
        = simple_form_for [@lead, Note.new] do |n|
          = n.input :content, as: :text, input_html: {rows: 5, class: "field span9"}
          .span12.offset7
            = n.submit class: 'btn btn-primary'
    %br
    - if @lead.notes.present?
      - @lead.notes.each do |note|
        .well-white.span10
          = note.content


    

app/views/leads/web_form.html.haml
%h3 Web Form
Copy the form below and use it anywhere in your website.
=text_area_tag "web_form",(render file: 'leads/convert_form'), readonly: true, style: "width:850px; height:400px"
%br
=link_to "Back", dashboard_path, class: 'btn btn-primary'