config/routes.rb
RebelFoundation::Application.routes.draw do

  devise_for :users

  devise_scope :user do
    match "logout" => "devise/sessions#destroy", as: "logout"  
    match "login" => "devise/sessions#new", as: "login"  
    match "signup" => "devise/registrations#new", as: "signup"
    match "dashboard" => "users#dashboard", as: "dashboard"
    match "admin"=> "users#index", as: "admin"
  end

  match "web_to_lead" => "leads#new_web_lead", :as => "web_to_lead"
  match "create_lead" => "leads#create_web_lead", :as => "create_lead"
  match "generate" => "leads#external_form"
  
  resources :organizations
  resources :leads do
    resources :notes
  end

  resources :leads do
    member do
      get :convert
    end
  end

  resources :users do
    member do
      get :approve
    end
  end
  

  resources :tasks
  resources :contacts
  resources :accounts
  resources :opportunities
  
  
  root to: 'pages#index'
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rails CRM
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        .container
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.brand{:href => root_path, :name => "top"} Rails CRM
        .nav-collapse.collapse
          %ul.nav.pull-right
            - if current_user.present?
              %li
                = link_to 'Dashboard', :dashboard
              %li
                = link_to 'Leads', :leads
              %li
                = link_to 'Tasks', :tasks
              %li
                = link_to 'Contacts', :contacts              
              %li
                = link_to 'Accounts', :accounts
              %li
                = link_to 'Opportunities', :opportunities
              %li
                = link_to 'Edit profile', edit_user_registration_path
              - if current_user.present? && current_user.admin
                %li
                  = link_to 'Admin', :admin
              %li
                = link_to 'Logout', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Login', new_user_session_path
              %li
                = link_to 'Register', new_user_registration_path

    - if flash.present?
      %section
        - flash.each do |name, msg|
          %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
            / %a.close{"data-dismiss" => "alert"} &#215;
            = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) 

    .container
      - if current_user.present? && current_user.approved
        .span2.well
          %h4
            Quick Links
          %hr
          %ul.sidebar
            %li
              = link_to 'New Lead', new_lead_path
            %li
              = link_to 'New Task', new_task_path
            %li
              = link_to 'New Contact', new_contact_path
            %li
              = link_to 'New Account', new_account_path
            %li
              = link_to 'New Opportunity', new_opportunity_path
          %br
          %br
          %h4
            Settings
          %hr
          %ul.sidebar
            %li
              = link_to 'Web-to-Lead Form', web_to_lead_path
      .span8
        = yield